export const inputStyleConfig = {
  fontFamily: 'Open Sans',
  valueColor: '#4A5568',
  valueFontWeight: 500,
  placeholderColor: '#4A5568',
  placeholderDisabledColor: '#cbd5e0',
  labelColor: '#a0aec0',
  labelFontWeight: 500,
  helperTextColor: '#a0aec0',
  helperTextFontWeight: 500,
  helperTextFontSize: '12px',
  borderColor: '#E2E8F0',
  borderRadius: '6px',
  backgroundColor: '#ffffff',
  backgroundDisabledColor: '#F7FAFC',
  focusBorderColor: '#76ACFB',
  filledBackgroundColor: '#DEEBFC',
  filledFontColor: '#3385ff',
  searchBackgroundColor: '#f7fafc',
  iconColor: '#A0AEC0',
  errorColor: '#f16063',
  successColor: '#66cb9f',
}
